general:
  instance_name: "Local SearXNG"
  debug: false

server:
  secret_key: "replace-with-a-long-random-string"
  public_instance: false
  image_proxy: true
  limiter: true

ui:
  default_theme: simple

search:
  safe_search: 1
  autocomplete: "duckduckgo"
